apiVersion: v1
kind: Service
metadata:
  name: broadcast
  namespace: goxang-broadcast-system
  labels:
    app.kubernetes.io/name: broadcast
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: broadcast
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
