// Package clientset provides a minimal typed client for the
// networking.goxang.io/v1alpha1 Broadcast resource. It follows the same shape
// as the client generated by client-gen, but is hand-maintained to avoid a
// codegen toolchain for a single type.
package clientset

import (
	"context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/serializer"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/rest"

	"github.com/goxang/broadcast/api/networking/v1alpha1"
)

// Interface is the set of Broadcast operations used by the controller.
type Interface interface {
	Broadcasts(namespace string) BroadcastInterface
}

// BroadcastInterface exposes typed operations on Broadcasts.
type BroadcastInterface interface {
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1alpha1.Broadcast, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1alpha1.BroadcastList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	UpdateStatus(ctx context.Context, b *v1alpha1.Broadcast, opts metav1.UpdateOptions) (*v1alpha1.Broadcast, error)
}

// Clientset bundles the Broadcast client.
type Clientset struct {
	networking *networkingClient
}

// NewForConfig builds a Clientset from a rest.Config.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if err := setConfigDefaults(&configShallowCopy); err != nil {
		return nil, err
	}
	restClient, err := rest.RESTClientFor(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	return &Clientset{networking: &networkingClient{client: restClient}}, nil
}

// Broadcasts returns the client for Broadcast resources in namespace.
func (c *Clientset) Broadcasts(namespace string) BroadcastInterface {
	return &broadcastClient{client: c.networking.client, namespace: namespace}
}

// Scheme is the runtime scheme with the broadcast types registered. Used to
// build the serializer for the REST client.
var Scheme = runtime.NewScheme()

func init() {
	_ = v1alpha1.AddToScheme(Scheme)
}

var codecs = serializer.NewCodecFactory(Scheme)

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = codecs.WithoutConversion()
	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
	return nil
}

type networkingClient struct {
	client rest.Interface
}

type broadcastClient struct {
	client    rest.Interface
	namespace string
}

var _ BroadcastInterface = (*broadcastClient)(nil)

func (b *broadcastClient) Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1alpha1.Broadcast, error) {
	result := &v1alpha1.Broadcast{}
	err := b.client.Get().
		Namespace(b.namespace).
		Resource("broadcasts").
		Name(name).
		VersionedParams(&opts, parameterCodec).
		Do(ctx).
		Into(result)
	return result, err
}

func (b *broadcastClient) List(ctx context.Context, opts metav1.ListOptions) (*v1alpha1.BroadcastList, error) {
	result := &v1alpha1.BroadcastList{}
	err := b.client.Get().
		Namespace(b.namespace).
		Resource("broadcasts").
		VersionedParams(&opts, parameterCodec).
		Do(ctx).
		Into(result)
	return result, err
}

func (b *broadcastClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return b.client.Get().
		Namespace(b.namespace).
		Resource("broadcasts").
		VersionedParams(&opts, parameterCodec).
		Watch(ctx)
}

func (b *broadcastClient) UpdateStatus(ctx context.Context, bc *v1alpha1.Broadcast, opts metav1.UpdateOptions) (*v1alpha1.Broadcast, error) {
	result := &v1alpha1.Broadcast{}
	err := b.client.Put().
		Namespace(b.namespace).
		Resource("broadcasts").
		Name(bc.Name).
		SubResource("status").
		VersionedParams(&opts, parameterCodec).
		Body(bc).
		Do(ctx).
		Into(result)
	return result, err
}

var parameterCodec = runtime.NewParameterCodec(Scheme)
